<?php

if (! defined('ABSPATH')) {
	exit;
}

/**
 * WooCommerce Clover payment gateway.
 */
class WC_Clover_Gateway extends WC_Payment_Gateway
{

	/**
	 * Constructor.
	 */
	public function __construct()
	{
		$this->id                 = 'clover_gateway';
		$this->method_title       = __('Clover Payments', 'clover-gateway');
		$this->method_description = __('Accept credit and debit card payments via Clover with full order item sync.', 'clover-gateway');
		$this->has_fields         = true;
		$this->supports           = array(
			'products',
			'refunds',
		);

		$this->init_form_fields();
		$this->init_settings();

		$this->enabled              = $this->get_option('enabled', 'no');
		$this->title                = $this->get_option('title', __('Credit / Debit Card', 'clover-gateway'));
		$this->description          = $this->get_option('description', __('Pay securely with your credit or debit card via Clover.', 'clover-gateway'));
		$this->merchant_id          = $this->get_option('merchant_id');
		$this->api_token            = $this->get_option('api_token');
		$this->public_key           = $this->get_option('public_key');
		$this->private_key          = $this->get_option('private_key');
		$this->test_mode            = 'yes' === $this->get_option('test_mode', 'yes');
		$this->default_tax_rate_id  = $this->get_option('default_tax_rate_id', '');

		add_action('woocommerce_update_options_payment_gateways_' . $this->id, array($this, 'process_admin_options'));
		add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));

		// Display saved card details in WooCommerce admin order screen.
		add_action('woocommerce_admin_order_data_after_order_details', array($this, 'display_card_details_admin'), 10, 1);

		// Display card details in the order-totals table on the My Account / order-view page.
		add_filter('woocommerce_get_order_item_totals', array($this, 'add_card_details_to_order_totals'), 10, 3);

		// Display card details on PDF invoices generated by the WooCommerce PDF Invoices plugin.
		add_action('wpo_wcpdf_after_order_data', array($this, 'display_card_details_pdf'), 10, 2);
	}

	/**
	 * Admin settings fields.
	 */
	public function init_form_fields()
	{
		$this->form_fields = array(
			'enabled'      => array(
				'title'   => __('Enable/Disable', 'clover-gateway'),
				'type'    => 'checkbox',
				'label'   => __('Enable Clover Payments', 'clover-gateway'),
				'default' => 'no',
			),
			'test_mode'    => array(
				'title'       => __('Test Mode', 'clover-gateway'),
				'type'        => 'checkbox',
				'label'       => __('Enable Clover sandbox mode', 'clover-gateway'),
				'default'     => 'no',
				'description' => __('When enabled, all transactions will be sent to Clover sandbox endpoints.', 'clover-gateway'),
			),
			'title'        => array(
				'title'       => __('Title', 'clover-gateway'),
				'type'        => 'text',
				'default'     => __('Credit / Debit Card', 'clover-gateway'),
				'description' => __('This controls the title displayed to customers during checkout.', 'clover-gateway'),
				'desc_tip'    => true,
			),
			'description'  => array(
				'title'       => __('Description', 'clover-gateway'),
				'type'        => 'textarea',
				'default'     => __('Pay securely using your credit or debit card.', 'clover-gateway'),
				'description' => __('This controls the description shown to customers during checkout.', 'clover-gateway'),
				'desc_tip'    => true,
			),
			'merchant_id'  => array(
				'title'       => __('Merchant ID', 'clover-gateway'),
				'type'        => 'text',
				'description' => __('Your Clover Merchant ID (MID), e.g. F64XC5Q3ES9D1.', 'clover-gateway'),
				'desc_tip'    => true,
			),
			'api_token'    => array(
				'title'       => __('API Token', 'clover-gateway'),
				'type'        => 'password',
				'description' => __('Clover v3 REST API token for order creation. Must have read access to inventory/items so product names can be matched and tax applied.', 'clover-gateway'),
				'desc_tip'    => true,
			),
			'public_key'   => array(
				'title'       => __('Public Key', 'clover-gateway'),
				'type'        => 'text',
				'description' => __('Clover eCommerce API public key for iframe tokenization.', 'clover-gateway'),
				'desc_tip'    => true,
			),
			'private_key'  => array(
				'title'       => __('Private Key', 'clover-gateway'),
				'type'        => 'password',
				'description' => __('Clover eCommerce API private key for charging cards.', 'clover-gateway'),
				'desc_tip'    => true,
			),
			'default_tax_rate_id' => array(
				'title'       => __('Default Tax Rate ID', 'clover-gateway'),
				'type'        => 'text',
				'description' => __('Clover tax rate ID applied to every product line item in each order. This makes tax appear in Clover\'s Tax Report, not just on receipts. Use the "Browse Tax Rates" button below to find and select the correct rate.', 'clover-gateway'),
				'default'     => '',
				'placeholder' => 'e.g. ABCDE12345FGH',
			),
		);
	}

	/**
	 * Output payment fields on checkout.
	 */
	public function payment_fields()
	{
		if ($this->description) {
			echo wpautop(wp_kses_post($this->description));
		}

		if (! is_ssl()) {
			echo '<p><strong>' . esc_html__('Warning:', 'clover-gateway') . '</strong> ' . esc_html__('Your site is not using HTTPS. Clover requires HTTPS for live payments.', 'clover-gateway') . '</p>';
		}

		wc_get_template(
			'payment-form.php',
			array(
				'gateway'    => $this,
				'public_key' => $this->public_key,
				'test_mode'  => $this->test_mode,
			),
			'',
			WC_CLOVER_GATEWAY_PLUGIN_DIR . 'templates/'
		);
	}

	/**
	 * Enqueue checkout scripts.
	 */
	public function enqueue_scripts()
	{
		if (! is_checkout() || ! $this->is_available()) {
			return;
		}

		$sdk_url = $this->test_mode
			? 'https://checkout.sandbox.dev.clover.com/sdk.js'
			: 'https://checkout.clover.com/sdk.js';

		wp_register_script(
			'clover-sdk',
			$sdk_url,
			array(),
			null,
			true
		);

		wp_register_script(
			'clover-checkout',
			WC_CLOVER_GATEWAY_PLUGIN_URL . 'assets/js/clover-checkout.js',
			array('jquery', 'wc-checkout', 'clover-sdk'),
			WC_CLOVER_GATEWAY_VERSION,
			true
		);

		wp_localize_script(
			'clover-checkout',
			'wc_clover_params',
			array(
				'public_key'    => $this->public_key,
				'test_mode'     => $this->test_mode ? 'yes' : 'no',
				'ajax_url'      => admin_url('admin-ajax.php'),
				'gateway_id'    => $this->id,
				'error_generic' => __('Payment could not be processed. Please try again.', 'clover-gateway'),
				'error_invalid' => __('Please check your card details and try again.', 'clover-gateway'),
				'error_token'   => __('Card information incomplete. Please fill all fields.', 'clover-gateway'),
			)
		);

		wp_enqueue_script('clover-sdk');
		wp_enqueue_script('clover-checkout');

		wp_enqueue_style(
			'clover-checkout',
			WC_CLOVER_GATEWAY_PLUGIN_URL . 'assets/css/clover-checkout.css',
			array(),
			WC_CLOVER_GATEWAY_VERSION
		);
	}

	/**
	 * Validate fields.
	 *
	 * @return bool
	 */
	public function validate_fields()
	{
		return true;
	}

	/**
	 * Process payment.
	 *
	 * @param int $order_id Order ID.
	 *
	 * @return array
	 */
	public function process_payment($order_id)
	{
		$order = wc_get_order($order_id);

		if (method_exists($order, 'calculate_totals')) {
			$order->calculate_totals();
		}

		// Duplicate prevention: already processed.
		$existing_order_id = get_post_meta($order_id, '_clover_order_id', true);
		if (! empty($existing_order_id)) {
			return array(
				'result'   => 'success',
				'redirect' => $this->get_return_url($order),
			);
		}

		$card_token  = isset($_POST['clover_card_token']) ? sanitize_text_field(wp_unslash($_POST['clover_card_token'])) : '';
		$will_charge = ! empty($card_token)
			&& 'order_only' !== $card_token
			&& preg_match('/^[a-zA-Z0-9_-]+$/', $card_token);

		$api = new Clover_API(
			$this->merchant_id,
			$this->api_token,
			$this->public_key,
			$this->private_key,
			$this->test_mode,
			$this->default_tax_rate_id
		);

		// Step 1: Create Clover order with real item names.
		$clover_order = $api->create_order_with_items($order);

		if (empty($clover_order['success'])) {
			$message = ! empty($clover_order['message'])
				? $clover_order['message']
				: __('Order could not be sent to Clover. Please try again.', 'clover-gateway');

			wc_add_notice($message, 'error');

			return array('result' => 'fail');
		}

		$clover_order_id = $clover_order['clover_order_id'];
		$amount_cents    = (int) round((float) $order->get_total() * 100);

		// Save order ID immediately to prevent duplicate syncs from status hook.
		update_post_meta($order_id, '_clover_order_id', $clover_order_id);
		update_post_meta($order_id, '_clover_amount_cents', $amount_cents);

		// No card token — COD / pay on pickup via Clover gateway.
		// Order is created and sent to Clover printers but remains Open until paid on device.
		if (! $will_charge) {
			$api->fire_order( $clover_order_id, $order->get_id() );

			$order->update_status(
				'on-hold',
				__('COD order placed. Order sent to Clover — payment on pickup/delivery.', 'clover-gateway')
			);
			$order->save();
			$order->add_order_note(
				sprintf(
					/* translators: 1: Clover order ID, 2: formatted order total */
					__('Clover order created (COD, no charge). Clover Order ID: %1$s | Total: %2$s', 'clover-gateway'),
					$clover_order_id,
					wc_price($amount_cents / 100, array('currency' => $order->get_currency()))
				)
			);

			return array(
				'result'   => 'success',
				'redirect' => $this->get_return_url($order),
			);
		}

		// Step 2: Charge card against the Clover order.
		$charge = $api->charge_card(
			$card_token,
			$amount_cents,
			$clover_order_id,
			$order
		);

		if (empty($charge['success'])) {
			$message = ! empty($charge['message'])
				? $charge['message']
				: __('Payment could not be processed. Please try again.', 'clover-gateway');

			wc_add_notice($message, 'error');

			return array('result' => 'fail');
		}

		$charge_id  = $charge['charge_id'];
		$payment_id = isset($charge['payment_id']) ? $charge['payment_id'] : '';
		$card_brand = isset($charge['card_brand']) ? $charge['card_brand'] : '';
		$card_last4 = isset($charge['card_last4']) ? $charge['card_last4'] : '';

		// Step 3: Fire order to kitchen/printer (best-effort — non-fatal).
		$api->fire_order( $clover_order_id, $order->get_id() );

		// Step 4: Mark WooCommerce order as paid.
		$order->payment_complete($charge_id);

		// Step 5: Persist charge and card details to order meta.
		update_post_meta($order_id, '_clover_charge_id', $charge_id);

		if ($payment_id) {
			update_post_meta($order_id, '_clover_payment_id', $payment_id);
		}
		if ($card_brand) {
			update_post_meta($order_id, '_clover_card_brand', $card_brand);
		}
		if ($card_last4) {
			update_post_meta($order_id, '_clover_card_last4', $card_last4);
		}
		if (! empty($charge['card_exp_month']) && ! empty($charge['card_exp_year'])) {
			update_post_meta(
				$order_id,
				'_clover_card_exp',
				$charge['card_exp_month'] . '/' . $charge['card_exp_year']
			);
		}
		if (! empty($charge['tender_label'])) {
			update_post_meta($order_id, '_clover_tender_label', $charge['tender_label']);
		}

		// Build the human-readable card summary for the order note.
		$card_summary = '';
		if ($card_brand && $card_last4) {
			$card_summary = sprintf(' | %s ending in %s', $card_brand, $card_last4);
		}

		$order->add_order_note(
			sprintf(
				/* translators: 1: Clover charge ID  2: Clover order ID  3: card summary */
				__('Clover payment successful. Charge ID: %1$s | Clover Order ID: %2$s%3$s', 'clover-gateway'),
				$charge_id,
				$clover_order_id,
				$card_summary
			)
		);

		return array(
			'result'   => 'success',
			'redirect' => $this->get_return_url($order),
		);
	}

	/**
	 * Process refund.
	 *
	 * @param int    $order_id Order ID.
	 * @param float  $amount   Amount to refund.
	 * @param string $reason   Reason.
	 *
	 * @return bool|\WP_Error
	 */
	public function process_refund($order_id, $amount = null, $reason = '')
	{
		$order                 = wc_get_order($order_id);
		$charge_id             = get_post_meta($order_id, '_clover_charge_id', true);
		$amount_cents_original = (int) get_post_meta($order_id, '_clover_amount_cents', true);

		if (empty($charge_id) || $amount_cents_original <= 0) {
			return new WP_Error(
				'clover_refund_missing',
				__('Clover charge information not found for this order.', 'clover-gateway')
			);
		}

		if (null === $amount) {
			$amount = $order->get_total();
		}

		$amount_cents = (int) round((float) $amount * 100);

		$api = new Clover_API(
			$this->merchant_id,
			$this->api_token,
			$this->public_key,
			$this->private_key,
			$this->test_mode
		);

		$result = $api->refund(
			$charge_id,
			$amount_cents,
			empty($reason) ? 'requested_by_customer' : $reason
		);

		if (empty($result['success'])) {
			return new WP_Error(
				'clover_refund_failed',
				__('Refund could not be processed. Please try again.', 'clover-gateway')
			);
		}

		$order->add_order_note(
			sprintf(
				__('Refunded %1$s via Clover. Charge ID: %2$s', 'clover-gateway'),
				wc_price($amount),
				$charge_id
			)
		);

		return true;
	}

	// -------------------------------------------------------------------------
	// Card detail display helpers
	// -------------------------------------------------------------------------

	/**
	 * Retrieve stored card details for a given order.
	 *
	 * Returns an array with 'brand' and 'last4' keys, or false when the order
	 * was not paid via this gateway or no card data was recorded.
	 *
	 * @param WC_Order|int $order Order object or order ID.
	 * @return array|false
	 */
	public function get_card_details_for_order($order)
	{
		if (! ($order instanceof WC_Order)) {
			$order = wc_get_order($order);
		}
		if (! $order || $order->get_payment_method() !== $this->id) {
			return false;
		}

		$order_id = $order->get_id();
		$brand    = get_post_meta($order_id, '_clover_card_brand', true);
		$last4    = get_post_meta($order_id, '_clover_card_last4', true);

		if (empty($brand) || empty($last4)) {
			return false;
		}

		return array(
			'brand'      => $brand,
			'last4'      => $last4,
			'exp'        => get_post_meta($order_id, '_clover_card_exp', true),
			'summary'    => sprintf('%s ending in %s', $brand, $last4),
			'payment_id' => get_post_meta($order_id, '_clover_payment_id', true),
			'tender'     => get_post_meta($order_id, '_clover_tender_label', true),
		);
	}

	/**
	 * Show card details panel in the WooCommerce admin order edit screen.
	 *
	 * Mirrors the `woocommerce_admin_order_data_after_order_details` hook used
	 * by the official Clover Payments for WooCommerce plugin.
	 *
	 * @param WC_Order $order Current order.
	 */
	public function display_card_details_admin($order)
	{
		$details = $this->get_card_details_for_order($order);
		if (! $details) {
			return;
		}
		?>
		<br class="clear" />
		<h4><?php esc_html_e('Payment Information', 'clover-gateway'); ?></h4>
		<br class="clear" />
		<p><?php echo esc_html($details['summary']); ?></p>
		<?php
		if (! empty($details['exp'])) {
			echo '<p>' . esc_html(
				sprintf(
					/* translators: expiry date */
					__('Expires: %s', 'clover-gateway'),
					$details['exp']
				)
			) . '</p>';
		}
	}

	/**
	 * Append a "Card" row to the order-totals table shown on the My Account
	 * order detail page and the checkout thank-you page.
	 *
	 * @param array    $total_rows Existing rows.
	 * @param WC_Order $order      Current order.
	 * @return array
	 */
	public function add_card_details_to_order_totals($total_rows, $order)
	{
		$details = $this->get_card_details_for_order($order);
		if (! $details) {
			return $total_rows;
		}

		// Insert the card row just before the order total so the layout mirrors
		// what the official Clover plugin produces.
		$order_total = $total_rows['order_total'];
		unset($total_rows['order_total']);

		$total_rows['clover_card_details'] = array(
			'label' => __('Card:', 'clover-gateway'),
			'value' => esc_html($details['summary']),
		);

		$total_rows['order_total'] = $order_total;

		return $total_rows;
	}

	/**
	 * Append card details to PDF invoices generated by the
	 * WooCommerce PDF Invoices & Packing Slips plugin.
	 *
	 * @param string   $template_type Template type (invoice | packing-slip | etc.).
	 * @param WC_Order $order         Current order.
	 */
	public function display_card_details_pdf($template_type, $order)
	{
		if ('invoice' !== $template_type) {
			return;
		}

		$details = $this->get_card_details_for_order($order);
		if (! $details) {
			return;
		}
		?>
		<tr class="payment-method">
			<th></th>
			<td><?php echo esc_html($details['summary']); ?></td>
		</tr>
		<?php
	}
}
